# Paths
all_video_names: list/all.video
video_path: ~/lsma/video
downsampled_videos: downsampled_videos
surf_features: surf

# downsampling
downsampling_frame_len: 60
downsampling_frame_rate: 15
keyframe_interval: 10

# surf
hessian_threshold: 400
kmeans_cluster_num: 256